version: "3.9"

services:
#  db:
#    container_name: db
#    image: postgres:14.0-alpine
#    hostname: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
#    environment:
#      - POSTGRES_PORT=${POSTGRES_PORT}
#      - POSTGRES_HOST=${POSTGRES_HOST}
#      - POSTGRES_NAME=${POSTGRES_NAME}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#    ports:
#      - "5431:5432"
#    restart: always
  tg_bot:
    build: .
    command: [ "python", "-u", "main.py" ]
    restart: always
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=db
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - MAIL_LOGIN=${MAIL_LOGIN}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}